services:
  bookingservice.api:
    image: ${DOCKER_REGISTRY-}bookingserviceapi
    build:
      context: .
      dockerfile: Services/BookingService/BookingService.API/Dockerfile

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: Services/CatalogService/CatalogService.API/Dockerfile
